import type { Metadata } from "next";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "@/styles/index.css";
import "@/styles/tailwind.css";
import "@/styles/fonts.css";
export const metadata: Metadata = {
  title: "Limeneer Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-azonix">{children}</body>
    </html>
  );
}
